language: objective-c
osx_image: xcode9

before_install:
   - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet

script:
   - xcodebuild test -project Autolycus.xcodeproj -scheme AutolycusTests -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.0'
   - pod lib lint --quick
