language: objective-c
osx_image: xcode11.1

before_install:
- travis_wait 30 pod install

script:
   - xcodebuild test -project Autolycus.xcodeproj -scheme AutolycusTests -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.1'
   - pod lib lint --quick
